/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package templato;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.*;



public class LibraryTest {
    
	@Test 
	public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
     

    }
}
