# This worksflow musing gradel to gernaret javadoc and then moves the
# generated files to the docs/javadoc directory. They ar then subsequently
# appears in the github pages.

name: Javadoc generation

on:
  push:
    branches: [ main, dev ]
    # paths: [ '**.java' ]

jobs:
  api-website:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Set up the Java JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build javadocs with Gradle
      run: ./gradlew javadoc

    - name: Deploy Javadoc to GH Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: dev # The branch the action should deploy to.
        folder: semplate-lib/build/docs/javadoc # The folder the action should deploy.
        target-folder: docs/javadoc
