# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Deploy Javadocs

on:
   push:
     branches: [ dev ]

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout ️
        uses: actions/checkout@v2.3.1
      - name: Build Javadocs
        run: |
             echo "Building javadocs with gradle"
             ./gradlew javadoc
             echo "Moving to javadocs directory:"
             cd semplate-lib/build/docs/javadoc/
             echo "Creating .nojekyll to have Github pages deploy html as is:"
             touch .nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
           branch: docs # The branch the action should deploy to.
           folder: semplate-lib/build/docs/javadoc/ # The folder the action should deploy.
